### ISSUE TITLE
Review progress and discuss next steps

### ISSUE THREAD

**Issue by z-y-huang** [gslab-econ/gslab_make#25]
Hi @gentzkow:

I've been updating `gslab_make` and `template` to some best practices and wanted to get your feedback.

1. I added some community standards documents (#23).
   * I added an [issue template](https://github.com/gentzkow/gslab_make/blob/30f7842a911f1bc97183f7cf9b097b8bc763ee2f/.github/ISSUE_TEMPLATE/issue-template.md) and [pull request template](https://github.com/gentzkow/gslab_make/blob/30f7842a911f1bc97183f7cf9b097b8bc763ee2f/.github/pull-request-template.md) that autopopulate whenever someone opens an issue or pull request. Let me know I should make any edits to these.

2. I migrated the documentation to [Sphinx](http://www.sphinx-doc.org/en/master/) (#22). As a demo, I'm currently hosting it on my [forked version](https://z-y-huang.github.io/gslab_make/) of `gslab_make` (I don't have access for the main repository). I'm still playing around with some of the auto-documentation functionalities, but let me know if there's anything about the layout I should change.

In terms of next steps:

1. I want to revamp the unit tests (#9) and switch to continuous testing (I was thinking about using [Travis CI](https://docs.travis-ci.com/user/for-beginners/)).
2. I need to wrap up some of the changes I was making to `gslab_make`, `template`, and `ra-manual` as a response to the data editor reviews from `SocialMediaEffects`.
3. I did a [first pass](https://github.com/gentzkow/template/issues/23) at creating real examples for the template and need to continue building on them. 

How do you think I should best prioritize the next steps?

**Comment by gentzkow** [comment]
Thanks @z-y-huang. Just noting that I received this. Trying to work through some more urgent things in the queue but I'll try to look this over as soon as I can. 

If you have bandwidth and want to push ahead on whichever of (1)-(3) seem highest priority to you that would be great.

One thought: The feedback from Lars V (data editor at AER) and a subsequent phone conversation I had with him reinforced for me just how strong the benefit of simplicity. I've thought of our current template as very simple (in contrast to the super complicated SCons one). It was striking to me that from Lars' perspective it was super complicated and required significant work to understand / debug.

A few things that's led me to consider:

(1) We could consider making the /input/ and /external/ link creation optional and allow code in simple repositories to make cross-directory and external calls directly. We could obtain some of the benefit of inputs.txt and externals.txt by having a script that scans code and reports all the input / external directories being called as part of the logging.

(2) We could consider building an option to have a Stata-only flavor of the repo where we use Stata scripts to replicate the gslab_make functionality.

(3) We could build an export tool (as Lars suggested) that would create a replication archive that does not require use of gslab_make (e.g., outputting lists of the command line calls that the make.py scripts generate).

**Comment by gentzkow** [comment]
@z-y-huang Thanks again. I've now looked this over.

I like the idea of issue and pull request templates. Before I propose edits to the details, can you tell me a bit more about how these work? If Github sees these files in the /.github/ directory of a repo it uses them as templates for all issues / pull requests in that repo? If so, should those live in `template` rather than `gslab_make`?

On the documentation, the format is great. The main thing I'd want to think more about is the organization -- how to foreground the basic functions and the simple goal of using gslab_make to run code in sequence from multiple programs while pushing less essential details to later sections. Happy to discuss.

**Comment by gentzkow** [comment]
@z-y-huang One other thought on simplification. What would you think about getting rid of the setup_stata step and instead storing all Stata ado files locally in the /lib/ directory of the repo? We'd then need to add code to the top of Stata do files to add that /lib/ directory to the path and to *remove* the local Stata ado directory (so there's no risk of accidentally relying on a command installed locally)?

We could consider the same for R. My guess would have been all the R packages and dependencies are too big to store locally but maybe not.

**Comment by gentzkow** [comment]
@z-y-huang Can you give me an update here? It would be great if we can integrate this discussion into some next steps and close out this issue.

**Comment by z-y-huang** [comment]
@gentzkow:

Apologies, I was working on revamping the unit tests and it's taking longer than expected. For the items I listed [here](https://github.com/gentzkow/gslab_make/issues/25#issue-509358099), I pushed my first attempts at real example scripts to master. I am prioritizing unit testing over any new changes to ensure nothing breaks.

**Thoughts on this [comment](https://github.com/gentzkow/gslab_make/issues/25#issuecomment-546446349):**

1. One difficulty here is that it can be hard to systematically determine what is a path. For example, it's not immediately obvious to me how we would determine whether the string `"input"` refers to a path or just a string.

2. My impression is that what most people find difficult about using `gslab_make` is the set up process for command line usage and the linking framework (related to [1]). 

   I'm not sure there's an easy way to simplify the former as long as we're using multiple applications and the problem isn't really solved by exporting system commands. I looked into dockers, but they don't play nicely with licensed software (e.g., Stata, Matlab). I'm also not sure what the overlap is between people who know how to use dockers and people who don't know how to update their system paths.

  The latter is definitely something that could be improved. One thought is that the export tool could remove the linking framework, though we would encounter the issue in [1] where we would need a good way to tell apart paths from strings.

In terms of this [comment](https://github.com/gentzkow/gslab_make/issues/25#issuecomment-555223004):

1. Yes, Github converts the files in `/.github/` to templates. The idea would be that we would have the issue and pull request templates for every repository. I started out with `gslab_make` just to complete the checklist Github suggested, but I can copy them over to `template`).
2. I made some edits to the documentation to make it clearer what functionalities the module has. I can continue working on it to prioritize the important functionalities. Can I get repository permissions to create a Github page for `gslab_make`?

For this [comment](https://github.com/gentzkow/gslab_make/issues/25#issuecomment-560032925):

1. This is what I've been doing for SME/PA since the Microsoft RAs have had issues with downloading Stata packages. I can change the template to adopt this. This definitely wouldn't work for Python, and probably won't work for R given the size and number of libraries that would need to be installed locally.

**Comment by gentzkow** [comment]
Great. Thanks!

On determining what is a path, what about if we require all scripts to define a global variable ROOT corresponding to the root of the repository and then require all references to paths outside a module to be written as $ROOT/directory/... Then we just search for paths beginning with ROOT?

There will still be an issue if people are doing something complicated like building paths using code and then calling them as variable names. We could require in those cases that people include a comment or output file listing the relevant $ROOT/... directories so they get slurped up by our scanner.

It seems to me if linking is no longer mandatory we could get people to pay the cost of setting up command line usage. Seems like we just need to focus attention on writing super clear documentation for this and good tests people can run to verify their setup before they try to run the actual repo. Also, this is another reason why having a Stata-only flavor that doesn't use gslab_make at all would be valuable for baby users.

I don't see off hand how to change your permissions for `gentzkow/gslab_make`. The permissions structure is different from the repos that are part of the gslab_econ org and I don't think we can make it granular (see [here](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/permission-levels-for-a-user-account-repository#collaborator-access-on-a-repository-owned-by-a-user-account)). I can copy the repo to gslab_econ if you think that's the best approach.

Let's make the switch for Stata packages in the repo template. We should document clearly the procedure people are supposed to follow and make sure the code templates are written so they can't call locally installed ado files. (Otherwise people will commit code that requires local ado files to run and it will break when others try to use it.)

Misc: Have you seen this [template](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/permission-levels-for-a-user-account-repository#collaborator-access-on-a-repository-owned-by-a-user-account) functionality in Github? Should we be using it?

**Comment by z-y-huang** [comment]
@gentzkow:

1. How would we want to deal with external dependencies? Or would external dependencies be out of the scope of the baby version? One thought is having a centralized module (e.g., `external`) for external dependencies and users could refer to it with `$ROOT/external/`

2. I think moving the repo to `gslab_econ` may be the best solution. It doesn't look like there's any way to give admin privileges to a collaborator outside of transferring the repository.
 
3. Will do.

4. That would probably be a good idea. Right now, we fork or manually copy, neither of which are ideal options.

**Comment by gentzkow** [comment]
(That was a reply to (1). For (2)-(4) all sounds good. I will execute the copy to `gslab_econ` this week.)

**Comment by gentzkow** [comment]
@z-y-huang Just transferred the gslab_make repo to gslab-econ and gave you admin permissions. I will go ahead and close this task.

**Comment by gentzkow** [comment]
** Summary **

In this task we mapped next steps for the template / gslab_make tools. We agreed on the following next steps which @z-y-huang will implement:
* Revamp the unit tests (#9) and switch to continuous testing (I was thinking about using Travis CI).
* Wrap up some of the changes to gslab_make, template, and ra-manual as a response to the data editor reviews from SocialMediaEffects.
* Continue improving real examples for the template
* Continue improving documenation
* Allow direct calls without using inputs.txt per (1) [here](https://github.com/gslab-econ/gslab_make/issues/25#issuecomment-546446349) and subsequent discussion
* Store Stata add on tools locally per [this comment](https://github.com/gslab-econ/gslab_make/issues/25#issuecomment-560032925)

@z-y-huang Feel free to edit if I've missed anything
