### ISSUE TITLE
Fix run_latex hanging errors

### ISSUE THREAD

**Issue by Houdanait** [gslab-econ/gslab_make#33]
Following the conversion of [Gentzkow/VirusAffect ](https://github.com/gentzkow/VirusAffect/issues/40) paper.lyx and SI.lyx to latex format, it turns out that the function run_latex defined [here](https://github.com/gslab-econ/gslab_make/blob/3bab783c7f45700e82031e27eb47157508c0ca54/gslab_make/run_program.py#L214) does not return an error when there actually is a LaTeX error. 

Therefore instead of displaying an error message on terminal and quitting, it runs forever on terminal without exiting. 

Task list
- [x] Fix the run_latex function so that it stops running when encountering an error and that it displays the error message 

@zkashner  fyi

**Comment by zkashner** [comment]
@Houdanait made the change you requested in branch.

**Comment by Houdanait** [comment]
thanks @zkashner !!

**Comment by Houdanait** [comment]
Hi @gentzkow,
I have been working on making a few amendments to the gslab_make latex and matlab functions, and I think being admin of gslab does not grant permissions to make changes on this repo.  So, for now I ask @zkashner to implement the changes when i arrive to them. I was wondering whether you think there would be a more efficient way to operate, if I or someone else could also be granted access since he is leaving soon? thank you so much!!

**Comment by gentzkow** [comment]
Well that's easy to fix! I just added you as an admin in the gslab_make
repo.

We should make a note that before Zane leaves he should transfer to you all
of his "super RA" permissions / responsibilities.

>

**Comment by Houdanait** [comment]
Perfect @gentzkow , thank you!! note made!

**Comment by Houdanait** [comment]
Closing this issue as the implemented change has been merged to master in PR #34. 

Summary of this issue: the goal of this issue was to figure out why gslab run_latex does not exit when encouring an error and hangs in terminal. After some work, this issue turn out to be related to another [matlab hanging error ](https://github.com/gslab-econ/gslab_python/issues/166). Adding a timeout option in ProgramDirective.py solves the issue.

**Comment by zkashner** [comment]
@Houdanait this fix actually does not compile for Python 2.7. Do you think you could take a second look and ensure it is robust to both versions?

**Comment by z-y-huang** [comment]
@zkashner, @Houdanait: Whoops, I fixed this issue locally over winter break but never had the time to update the public repo (the joys of first-year).

`subprocess.wait()` [deadlocks](https://docs.python.org/3/library/subprocess.html) if the process generates too much output, which tends to happen when LaTeX or Matlab runs into an error, since they spit out abajillion error messages. (We need the `subprocess.wait()` command when using the shell to create/delete directories/files since otherwise we run into timing issues during execution.)

The timeout argument doesn't work for Python 2.7 since I'm using a custom `subprocess` that fixes a bug in Python 2.7 for Windows encoding (yay deprecation). A quick fix that is compatible for both Python 2.7 and 3.7 is to not execute `subprocess.wait()` during subprocess calls for programs, e.g.:

<img width="976" alt="Screen Shot 2021-03-19 at 1 52 59 PM" src="https://user-images.githubusercontent.com/40323298/111841080-9fba1880-88ba-11eb-8e54-9f54c6269edf.png">

<img width="1249" alt="Screen Shot 2021-03-19 at 1 52 16 PM" src="https://user-images.githubusercontent.com/40323298/111841076-9df05500-88ba-11eb-9ecf-ab438da4f7aa.png">

**Comment by z-y-huang** [comment]
Also the CI testing actually caught something and my efforts weren't in vain!

**Comment by Houdanait** [comment]
@z-y-huang wow thank you so much for this!!!
Let me revert back to `Python 2.7` and run to implement!

**Comment by jc-cisneros** [comment]
@gentzkow @jmshapir my sense is that there are no remaining relevant changes here to be merged to master through a PR. My vote would be to close this issue.

**Comment by jmshapir** [comment]
@jc-cisneros fine with me thanks!

**Comment by gentzkow** [comment]
@jc-cisneros OK by me too!
